services:
  periodic-nest:
    container_name: periodic_nest
    build:
      context: .
    env_file:
      - .production.env
    ports:
      - '5002:5002'
    command: node dist/main.js
    depends_on:
      - periodic_postgres
    restart: always

  periodic_postgres:
    container_name: periodic_postgres
    image: postgres:17
    env_file:
      - .production.env
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5434:5432'
    volumes:
      - periodic_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  periodic_postgres_data:
